# Generated by Django 2.2.4 on 2019-08-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='honorific',
            field=models.SmallIntegerField(choices=[(1, 'Mr'), (2, 'Mme')], default=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
