# Generated by Django 2.2.4 on 2019-08-23 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20190823_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('honorific', models.SmallIntegerField(choices=[(1, 'Mr'), (2, 'Mme')], default=1)),
            ],
        ),
    ]
