# Generated by Django 2.2.4 on 2019-08-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(blank=True, default='Patient', max_length=254),
        ),
    ]
